[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
myst-parser = "^4.0.0"
Sphinx = "^8.1.3"
sphinx-autobuild = "2024.10.3"
sphinx-copybutton = "^0.5.2"
sphinx-markdown-tables = "^0.0.17"
sphinx_rtd_theme = "^3.0.0"
