name: Build & Deploy Documentation
on:
  pull_request:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Sphinx documentation build
        uses: ammaraskar/sphinx-action@8.1.3
        with:
          docs-folder: "./"
        env:
          SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.SPHINX_GITHUB_CHANGELOG_TOKEN }}
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: _build/html/
